# Generated by Django 5.0.3 on 2024-03-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='order_items',
            field=models.ManyToManyField(related_name='shipped_items', to='store.orderitem'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.address'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
