# Generated by Django 5.0.3 on 2024-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ship_order_items_alter_ship_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
