# Generated by Django 5.0.3 on 2024-03-29 07:06

import common.validators.percent_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ship_is_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('percentage', models.PositiveIntegerField(blank=True, null=True, validators=[common.validators.percent_validator.percentage_validator])),
                ('minimum_cart_price', models.PositiveIntegerField()),
                ('currency_discount_applied', models.PositiveIntegerField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('Shipment failed', 'Shipment failed'), ('Shipment success', 'Shipment success'), ('Order is being processed', 'Order is being processed')], default='Order is being processed', max_length=30),
        ),
        migrations.CreateModel(
            name='DiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='store.cart')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.discount')),
            ],
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
